baseURL = 'https://kitans-grimoire.xyz/'
languageCode = 'en-us'
title = "kitan's Apprentice Witch Grimoire"
theme = "risotto"


[Params]
    mainSections = ["post"]
    intro = true
    headline = "Apprentice Witch Grimoire"
    description = "A guide for new magic users"
    github = "https://github.com/needfish"
    twitter = "https://twitter.com/XXX"
    email = "kitan.3p@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"