baseURL = 'https://needfish.github.io/apprentice-magic-grimoire'
languageCode = 'en-us'
title = "kitan's Apprentice Witch Grimoire"
theme = "risotto"


[params]
noindex = false

[params.theme]
palette = "base16-atelier-estuary"

