baseURL = 'https://needfish.github.io/apprentice-magic-grimoire'
languageCode = 'en-us'
title = "kitan's Apprentice Witch Grimoire v1"
theme = "risotto"

paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "apprentice magic grimoire"
description = "a guide for new magic users, circa 2024"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-youtube"
title = "youtube"
url = "https://www.youtube.com/channel/UCcBcqTjkCN8KsQwXcOLQwyw"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "discord"
url = "https://discord.gg/ydvxBzmpK9"


[menu]

  [[menu.main]]
    identifier = "introduction"
    name = "Intro"
    url = "/introduction/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true


